export type AppPage =
  | 'gate'
  | 'plants'
  | 'comparisons'
  | 'comparison'
  | 'growing-places'
  | 'journal'
  | 'harvest'
  | 'calendar'
  | 'search'
  | 'garden-notes'
  | 'garden-almanac'
  | 'plant-reference'
  | 'saved-sources'
  | 'library'
  | 'backup'